language: go
go:
  - "1.16"
branches:
  only:
    - develop
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.88.1/hugo_0.80.0_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
script:
  - hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  target_branch: master
  local-dir: public
  on:
    branch: develop
